import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Atividade Espírita",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_59203_Atividade Espírita.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://streaming31.hstbr.net:8230/live",
            active: true,
        },
        {
            name:"Feliz FM São Paulo",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_59897_Feliz FM São Paulo.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://cloud1.cdnseguro.com:5520/;",
            active: false,
        },
        {
            name:"Pregação 24 Horas",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_49476_Pregação 24 Horas.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm45.srvstm.com:7116/;",
            active: false,
        },
        {
            name:"Biblica Gospel FM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_77127_Biblica Gospel FM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-58.zeno.fm/sx8ythaes8quv?zs=",
            active: false,
        },
        {
            name:"Gospel Mix SP",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_78095_Gospel Mix SP.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://servidor30-2.brlogic.com:8252/live",
            active: false,
        },
        {
            name:"Rádio Gospel Adoradores",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_59491_Rádio Gospel Adoradores.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://servidor31-4.brlogic.com:8018/live",
            active: false,
        },
        {
            name:"Rádio Canção Nova AM Cachoeira Paulista",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_43282_Rádio Canção Nova AM Cachoeira Paulista.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://cloud1.cdnseguro.com:10114/stream",
            active: false,
        },
        {
            name:"Rádio Sorocaba Gospel FM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_32820_Rádio Sorocaba Gospel FM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm1.xcast.com.br:8758/;",
            active: false,
        },
        {
            name:"Rádio Gospel Amar",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_1751_Rádio Gospel Amar.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stm4.xcast.com.br:11896/;",
            active: false,
        },
        {
            name:"Rádio Ministério Gospel",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_87141_Rádio Ministério Gospel.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://srv2.braudio.com.br:7404/;",
            active: false,
        },
        {
            name:"RTM - Rádio Trans Mundial",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_98251_RTM - Rádio Trans Mundial.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://24983.live.streamtheworld.com/RADIOTRANSMUNDIALAAC_SC",
            active: false,
        },
        {
            name:"Vida 96.5 FM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_86983_Vida 96.5 FM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm21.painelcast.com:6856/live",
            active: false,
        },
        {
            name:"Igreja Assembleia de Deus",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_86995_Igreja Assembleia de Deus.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://autodj.radioprofissional.com:8168/;",
            active: false,
        },
        {
            name:"Rádio Gospel Cordeiro de Deus",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_38960_Rádio Gospel Cordeiro de Deus.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://servidor33.brlogic.com:8598/live",
            active: false,
        },
        {
            name:"Web Rádio Louvores que Edificam",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_83106_Web Rádio Louvores que Edificam.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://s32.maxcast.com.br:8116/live",
            active: false,
        },
        {
            name:"Radio Gospel Novo Amanhecer",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_36215_Radio Gospel Novo Amanhecer.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://live1.livemus.com.br:27416/;",
            active: false,
        },
        {
            name:"Radio Louvor Campina Grande",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_4758_Radio Louvor Campina Grande.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-42.zeno.fm/hu0e2ws2qzzuv?zs=",
            active: false,
        },
        {
            name:"Rádio BBN - Rede de Radiodifusão Bíblica",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_19479_Rádio BBN - Rede de Radiodifusão Bíblica.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://audio-edge-qse4n.yyz.g.radiomast.io/ec065d59-f358-48c9-a288-4efc797e5860",
            active: false,
        },
        {
            name:"Rádio Gospel Mix",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_57575_Rádio Gospel Mix.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-64.zeno.fm/suaz14430tzuv?zs=",
            active: false,
        },
        {
            name:"Louvor Sertanejo",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_9551_Louvor Sertanejo.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://radio.stmsrv.com:28506/",
            active: false,
        },
        {
            name:"Web Rádio Católica Santo Antônio",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_7105_Web Rádio Católica Santo Antônio.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://servidor34.brlogic.com:7106/live",
            active: false,
        },
        {
            name:"RÁDIO GOSPEL MIX WEB",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_95794_RÁDIO GOSPEL MIX WEB.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://server05.srvsh.com.br:8456/;",
            active: false,
        },
        {
            name:"Radio Gospel Deus é bom",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_34075_Radio Gospel Deus é bom.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stm19.xcast.com.br:12536/;",
            active: false,
        },
        {
            name:"Rádio Vivência Espírita",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_17063_Rádio Vivência Espírita.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://hts03.kshost.com.br:11674/live",
            active: false,
        },
        {
            name:"Radio Jesus a Vida",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_24398_Radio Jesus a Vida.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://servidor40-3.brlogic.com:8004/live",
            active: false,
        },
        {
            name:"Vida Sertaneja FM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_69781_Vida Sertaneja FM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm5.voxhd.com.br:7622/;",
            active: false,
        },
        {
            name:"Rádio Cristã Online",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_96991_Rádio Cristã Online.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://servidor40-3.brlogic.com:8004/live",
            active: false,
        },
        {
            name:"Evangélica FM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_45666_Evangélica FM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://server07.srvsh.com.br:8186/stream",
            active: false,
        },
        {
            name:"Estrela da Manhã",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_80369_Estrela da Manhã.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stm20.srvaudio.com.br:10950/stream",
            active: false,
        },
        {
            name:"Rádio Vitória FM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_23093_Rádio Vitória FM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://streaming04.hstbr.net:8156/live",
            active: false,
        },
        {
            name:"Rádio Tamandaré",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_76032_Rádio Tamandaré.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://s45.maxcast.com.br:8058/live",
            active: false,
        },
        {
            name:"Radio Shalom",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_75048_Radio Shalom.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm1.srvstm.com:9022/;",
            active: false,
        },
        {
            name:"Igreja Missão da Graça de Deus",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_40887_Igreja Missão da Graça de Deus.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stm13.xcast.com.br:9346/;",
            active: false,
        },
        {
            name:"Radio Atividade FM Evangélica 90.7 FM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_88283_Radio Atividade FM Evangélica 90.7 FM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm1.xcast.com.br:8758/;",
            active: false,
        },
        {
            name:"Gospel Music Play",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_89811_Gospel Music Play.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stream-50.zeno.fm/dpkfzgxk268uv?zs=",
            active: false,
        },
        {
            name:"Rádios Sagrada Família Araturi",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_12164_Rádios Sagrada Família Araturi.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm20.voxtreaming.com.br:6928/;",
            active: false,
        },
        {
            name:"Rádio Jesus Está Com Você",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_46123_Rádio Jesus Está Com Você.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://s07.maxcast.com.br:8154/live?id=1279546905397",
            active: false,
        },
        {
            name:"Nossa Web Rádio Gospel",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_65704_Nossa Web Rádio Gospel.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://stm4.srvstm.com:14794/;",
            active: false,
        },
        {
            name:"On Web Rádio Gospel",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_89925_On Web Rádio Gospel.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://hts03.kshost.com.br:11910/;",
            active: false,
        },
        {
            name:"Rádio Eloim",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_73937_Rádio Eloim.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://live9.livemus.com.br:27284/;",
            active: false,
        },
        {
            name:"Hinos CCB",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_62913_Hinos CCB.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://srv5.voxon.top:7116/stream",
            active: false,
        },
        {
            name:"Melodia Cabugi",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_86544_Melodia Cabugi.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm2.voxhd.com.br:7436/;",
            active: false,
        },
        {
            name:"Web Radio Verdade Gospel",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_72267_Web Radio Verdade Gospel.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://radio.stmsrv.com:8346/",
            active: false,
        },
        {
            name:"Rádio Amor Incondicional",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_37626_Rádio Amor Incondicional.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm2.audiplushd.com.br:7174/;",
            active: false,
        },
        {
            name:"Gospel Ceuh Music",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_30164_Gospel Ceuh Music.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://s14.maxcast.com.br:8096/live",
            active: false,
        },
        {
            name:"Rádio Vida FM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_65046_Rádio Vida FM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm5.stmsrv.com:8380/;",
            active: false,
        },
        {
            name:"Rádio TV ABM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_37302_Rádio TV ABM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://hts02.kshost.com.br:10280/live",
            active: false,
        },
        {
            name:"Radio LG",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_8661_Radio LG.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://centova2.ipstm.net/proxy/lightgospel/stream",
            active: false,
        },
        {
            name:"Rádio Difusora de Londrina 690 AM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_4191_Rádio Difusora de Londrina 690 AM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "http://stm12.srvstm.com:10774/;",
            active: false,
        },
        {
            name:"Rádio Exaltar",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_29553_Rádio Exaltar.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://servidor20.brlogic.com:7228/live",
            active: false,
        },
        {
            name:"Uirapuru Jaguaribana 91.5 FM",
            artist: "Music",
            cover: "https://dab-radios.org/admin_panel_crisradiobrasil/uploads/radios/radio_85042_Uirapuru Jaguaribana 91.5 FM.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://servidor17.brlogic.com:7450/live",
            active: false,
        },
    ];
}

export default chillHop;

